### ISSUE TITLE
Questions about BraTS Masks 

### ISSUE THREAD

**Issue by TheCarmelGuy** [shreyaspadhy/UNet-Zoo#11]
Do you have to convert the ground truth masks to a binary segmentation map? The original BraTS masks are multi-class and it seems like the network only has two classes.

**Comment by shreyaspadhy** [comment]
So, we combined all the tumor classes into one binary tumor class, and so we have only two classes. However, and I'll look into this in the next few days, but the UNet models can trivially be extended to have multiple classes.
