### ISSUE TITLE
A question about the DICELossMultiClass

### ISSUE THREAD

**Issue by xiaohu2015** [shreyaspadhy/UNet-Zoo#13]
Can you make a explanation about the implementation of DICELossMultiClass:
why use output[:, 1, :, :]?

**Comment by HadiZayer** [comment]
I'm assuming that in a multi-class dice loss, you'd calculate the dice loss for each label that is not background and then average them. In this case, there is only one label that is not background, so it's hard-coded for the first label. Even though this sorts of make it not multi-class.

**Comment by xiaohu2015** [comment]
@HadiZayer  Ok, I understand. You had better give a notice on the code.

**Comment by shreyaspadhy** [comment]
Yeah, @HadiZayer has it correct, it was a mistake on my part. Since I only used my UNet for two classes, I must have hard-coded that line during debugging. I'll make the necessary corrections. Thanks for bringing it to my attention!

**Comment by shreyaspadhy** [comment]
I've implemented multi-class DICE loss as of my last push.
