### ISSUE TITLE
No module named dataParser

### ISSUE THREAD

**Issue by TheCarmelGuy** [shreyaspadhy/UNet-Zoo#2]
Seems like when I attempt to run main.py, I get a 'No module named dataParser.' Might I be doing something wrong?

**Comment by shreyaspadhy** [comment]
Hi, could you tell me the exact line you get the error?

**Comment by TheCarmelGuy** [comment]
This was the full stacktrace:

Traceback (most recent call last):
  File "main.py", line 21, in <module>
    from data import BraTSDatasetUnet, BraTSDatasetLSTM
  File "/Users/komelmerchant/Desktop/Research_Zhang/ImageSeg_Repos/UNet-Zoo/data.py", line 9, in <module>
    from dataParser import getMaskFileName, getImg
ImportError: No module named dataParser

**Comment by shreyaspadhy** [comment]
Hi, it should be fixed now! I accidentally omitted the file when I made the repo, sorry about that!
