### ISSUE TITLE
Question about BDC-LSTM input.

### ISSUE THREAD

**Issue by ggsf13** [shreyaspadhy/UNet-Zoo#5]
Hi, I read the article of BDC-LSTM, it seems the inputs of it are just the mask resluts of U-net segmentation, is it right?

**Comment by shreyaspadhy** [comment]
Yes, you take three consecutive z-slices {z-1, z, z+1}, feed them into U-Net, get masks, and then feed into BDC-LSTM to get the final improved mask for {z}.

**Comment by ggsf13** [comment]
@shreyaspadhy so the inputs are just 3 images not a series of images?
