### ISSUE TITLE
how to prepare data for bdclstm.py

### ISSUE THREAD

**Issue by mingrui** [shreyaspadhy/UNet-Zoo#7]
Hi, how to prepare my data for training using bdclstm.py?

Thank you!

**Comment by shreyaspadhy** [comment]
The input to BDCLSTM is three feature maps that are output from a trained UNet model. So, if you have images {z-1, z, z+1}, you pass them through a pre-trained UNet, and pass the outputted feature maps to BDCLSTM. The code in main_bdclstm.py does this, you just need to specify the weights of your trained UNet model.

**Comment by mingrui** [comment]
thank you!

**Comment by mingrui** [comment]
looking at the code, it seems that the code is getting min and max of the entire data folder.

what happens when two slices of scan are from different patients?

For example `z-1` is from patient 001 and `z` is from patient 002?

**Comment by shreyaspadhy** [comment]
For BDCLSTM, you need that {z-1, z, z+1} are from the same patient, because you want to use the spatial correlation b/w consecutive slices of the same 3D volume.

**Comment by mingrui** [comment]
I think I understand what you are describing.

My question is at this part of the code:
https://github.com/shreyaspadhy/UNet-Zoo/blob/26dd712d7eb006f070ca69c0186bdcf2c352f18e/data.py#L141

there is no explicit check for file from the same patient?

**Comment by shreyaspadhy** [comment]
If I remember correctly, the files are named patientnum_scantype_zcoord_...

So, if I iterate through the files, as long as zcoord is not less than 0 (lowest possible coordinate), and not higher than 31 (highest possible coordinate), since the files are sorted, the check that it belongs to the same patient happens implicitly.

**Comment by mingrui** [comment]
aww... I see.
I don't have access to the brats dataset yet.
Thanks for the clarification!
